#!/bin/sh

APPDIR_MOUNT=$(dirname $(readlink -f "${0}"))

export PATH="${APPDIR_MOUNT}/usr/bin/":$PATH
export LD_LIBRARY_PATH="${APPDIR_MOUNT}/usr/lib/":$LD_LIBRARY_PATH

cd "${APPDIR_MOUNT}"

exec "./usr/bin/$1" # add rest of commands when this works